-- ================================================================
-- 003_seed_programa.sql  —  Catálogo canónico del programa Impulsa
-- 35 filas: 8 hitos, 12 formaciones, 4 CC, 3 mentorías, 4 sesiones, extras
-- ================================================================

insert into programa_etapas
  (codigo, nombre, fase, tipo, dia_min, dia_max,
   responsable_promora, ejecutor_promora, entregables, canal, descripcion, orden)
values

-- ── FASE I: Estrategia ──────────────────────────────────────────

('HITO_0', 'Onboarding y contrato firmado',
 'fase_i_estrategia', 'hito', 0, 1,
 'Gonzalo + Laura', 'Gonzalo',
 ARRAY['Contrato firmado', 'Acceso a herramientas'],
 'Presencial / Meet', 'Arranque oficial del programa. Firma de contrato, acceso a Notion, GoHighLevel y recursos.',
 1),

('TEORIA_1', 'Formación 1 — Mindset del agente premium',
 'fase_i_estrategia', 'teoria', 1, 7,
 'Gonzalo', 'Gonzalo',
 ARRAY['Material formativo', 'Ejercicio de posicionamiento personal'],
 'Teams / Drive', 'Mentalidad diferencial del agente de lujo: autoridad, presencia, paciencia.',
 2),

('TEORIA_2', 'Formación 2 — El mercado de lujo en España',
 'fase_i_estrategia', 'teoria', 1, 7,
 'Gonzalo', 'Gonzalo',
 ARRAY['Análisis de mercado provincial', 'Mapa de competidores'],
 'Teams / Drive', 'Radiografía del segmento prime por provincias. Datos, tendencias y oportunidades.',
 3),

('TEORIA_3', 'Formación 3 — Captación premium: estrategia y herramientas',
 'fase_i_estrategia', 'teoria', 7, 14,
 'Gonzalo + Marketing', 'Gonzalo',
 ARRAY['Guión de captación', 'Plantilla de presentación a propietario'],
 'Teams / Drive', 'Proceso de captación en el segmento alto. Scripts, objeciones y diferenciación.',
 4),

('HITO_1', 'Primera reunión estratégica con mentor',
 'fase_i_estrategia', 'hito', 7, 14,
 'Gonzalo', 'Gonzalo + Impulsado',
 ARRAY['Plan de acción inicial', 'Territorio definido'],
 'Meet / Presencial', 'Primera mentoría formal. Diagnóstico de punto de partida y diseño del territorio de trabajo.',
 5),

('TEORIA_4', 'Formación 4 — CRM y pipeline de ventas',
 'fase_i_estrategia', 'teoria', 14, 21,
 'Laura', 'Laura',
 ARRAY['Acceso configurado a GoHighLevel', 'Pipeline inicial creado'],
 'Teams / GoHighLevel', 'Uso operativo del CRM. Etapas del pipeline, seguimiento y automatizaciones básicas.',
 6),

('TEORIA_5', 'Formación 5 — Marketing personal y posicionamiento digital',
 'fase_i_estrategia', 'teoria', 14, 21,
 'Marketing', 'Patricia',
 ARRAY['Perfil LinkedIn optimizado', 'Propuesta de valor escrita'],
 'Teams / Drive', 'Construcción de marca personal online. LinkedIn, contenido premium y referencia de zona.',
 7),

('SESION_1', 'Sesión práctica 1 — Role play de captación',
 'fase_i_estrategia', 'sesion_practica', 21, 28,
 'Gonzalo', 'Gonzalo + Impulsado',
 ARRAY['Grabación de simulacro', 'Feedback estructurado'],
 'Meet', 'Práctica en vivo de llamada y visita de captación. El mentor actúa como propietario.',
 8),

('TEORIA_6', 'Formación 6 — Visitas premium: protocolo y presentación',
 'fase_i_estrategia', 'teoria', 21, 28,
 'Gonzalo', 'Gonzalo',
 ARRAY['Checklist visita premium', 'Ficha de propiedad tipo'],
 'Teams / Drive', 'Protocolo de visita al segmento alto. Preparación, ambiente y seguimiento post-visita.',
 9),

('HITO_2', 'Primer lead cualificado registrado en CRM',
 'fase_i_estrategia', 'hito', 21, 35,
 'Impulsado', 'Impulsado',
 ARRAY['Lead cualificado en GoHighLevel', 'Ficha de contacto completa'],
 'GoHighLevel', 'Hito de activación comercial: primer contacto real con potencial de operación.',
 10),

('MENTORIA_1', 'Mentoría 1 — Estratégica inicial',
 'fase_i_estrategia', 'mentoria', 28, 35,
 'Gonzalo', 'Gonzalo + Impulsado',
 ARRAY['Resumen de mentoría', 'Compromisos firmados'],
 'Meet / Presencial', 'Revisión de los primeros 30 días. Ajuste de estrategia y consolidación del territorio.',
 11),

('TEORIA_7', 'Formación 7 — Financiación y due diligence básico',
 'fase_i_estrategia', 'teoria', 28, 42,
 'Gonzalo', 'Gonzalo',
 ARRAY['Guía de financiación premium', 'Checklist due diligence'],
 'Teams / Drive', 'Fundamentos de financiación hipotecaria en el segmento alto y puntos clave legales.',
 12),

('TEORIA_8', 'Formación 8 — Elaboración de propuestas comerciales',
 'fase_i_estrategia', 'teoria', 35, 42,
 'Gonzalo + Marketing', 'Patricia',
 ARRAY['Plantilla de propuesta', 'Ejemplo real comentado'],
 'Teams / Drive', 'Construcción de la propuesta de valor para el propietario y el comprador.',
 13),

('SESION_2', 'Sesión práctica 2 — Presentación de propuesta real',
 'fase_i_estrategia', 'sesion_practica', 42, 49,
 'Gonzalo', 'Gonzalo + Impulsado',
 ARRAY['Propuesta presentada', 'Feedback del mentor'],
 'Meet', 'El impulsado presenta una propuesta real (o simulada) y recibe feedback detallado.',
 14),

('CC1', 'Check Control 1 — Evaluación estratégica inicial',
 'fase_i_estrategia', 'check_control', 42, 49,
 'Gonzalo + Laura', 'Gonzalo',
 ARRAY['Informe CC1', 'Plan de mejora si procede'],
 'Meet', 'Primera evaluación formal del programa. KPIs de actividad, posicionamiento y mentalidad.',
 15),

('HITO_3', 'Plan de acción comercial validado',
 'fase_i_estrategia', 'hito', 42, 56,
 'Gonzalo', 'Impulsado',
 ARRAY['Plan de acción escrito', 'Pipeline con 3+ contactos activos'],
 'Notion / GoHighLevel', 'El impulsado tiene un plan claro, territorio definido y pipeline en marcha.',
 16),

('TEORIA_9', 'Formación 9 — Negociación avanzada en el segmento premium',
 'fase_i_estrategia', 'teoria', 49, 56,
 'Gonzalo', 'Gonzalo',
 ARRAY['Casos prácticos de negociación', 'Guía de objeciones avanzadas'],
 'Teams / Drive', 'Técnicas de negociación para operaciones de alto valor. Gestión de emociones y poder.',
 17),

('MENTORIA_2', 'Mentoría 2 — Seguimiento comercial',
 'fase_i_estrategia', 'mentoria', 49, 56,
 'Gonzalo', 'Gonzalo + Impulsado',
 ARRAY['Resumen de mentoría', 'Objetivos para la Fase II'],
 'Meet / Presencial', 'Cierre de Fase I. Revisión de resultados y preparación para la fase de seguimiento.',
 18),

-- ── FASE II: Seguimiento ────────────────────────────────────────

('HITO_4', 'Pipeline activo con caso real en curso',
 'fase_ii_seguimiento', 'hito', 56, 63,
 'Impulsado', 'Impulsado',
 ARRAY['Caso real documentado en Notion', 'Propietario o comprador identificado'],
 'Notion / GoHighLevel', 'El impulsado tiene al menos una operación real avanzando en el pipeline.',
 19),

('TEORIA_10', 'Formación 10 — Cierre de operaciones y documentación',
 'fase_ii_seguimiento', 'teoria', 56, 63,
 'Gonzalo', 'Gonzalo',
 ARRAY['Checklist de cierre', 'Plantilla de seguimiento post-firma'],
 'Teams / Drive', 'Proceso completo de cierre: notaría, documentación, gestión de expectativas del cliente.',
 20),

('TEORIA_11', 'Formación 11 — Gestión de objeciones complejas',
 'fase_ii_seguimiento', 'teoria', 63, 70,
 'Gonzalo', 'Gonzalo',
 ARRAY['Banco de objeciones', 'Respuestas modeladas'],
 'Teams / Drive', 'Objeciones de precio, exclusividad y urgencia frecuentes en operaciones de lujo.',
 21),

('SESION_3', 'Sesión práctica 3 — Simulacro de cierre',
 'fase_ii_seguimiento', 'sesion_practica', 63, 70,
 'Gonzalo', 'Gonzalo + Impulsado',
 ARRAY['Grabación de simulacro', 'Feedback estructurado'],
 'Meet', 'Práctica de la fase final de negociación con cliente real o simulado.',
 22),

('CC2', 'Check Control 2 — Revisión a mitad de programa',
 'fase_ii_seguimiento', 'check_control', 63, 70,
 'Gonzalo + Laura', 'Gonzalo',
 ARRAY['Informe CC2', 'Ajuste de objetivos'],
 'Meet', 'Evaluación del progreso acumulado. KCD del mes, pipeline, formaciones y estado emocional.',
 23),

('HITO_5', 'Propuesta presentada a cliente final',
 'fase_ii_seguimiento', 'hito', 70, 77,
 'Impulsado', 'Impulsado',
 ARRAY['Propuesta enviada y documentada', 'Respuesta del cliente registrada'],
 'Notion / GoHighLevel', 'El impulsado ha presentado una propuesta formal a un cliente real.',
 24),

('TEORIA_12', 'Formación 12 — Referrals y red de contactos premium',
 'fase_ii_seguimiento', 'teoria', 70, 77,
 'Gonzalo + Marketing', 'Gonzalo',
 ARRAY['Mapa de red de contactos', 'Plan de referrals activo'],
 'Teams / Drive', 'Construcción de una red de referidores: arquitectos, asesores fiscales, family offices.',
 25),

('MENTORIA_3', 'Mentoría 3 — Pre-cierre y estrategia final',
 'fase_ii_seguimiento', 'mentoria', 70, 84,
 'Gonzalo', 'Gonzalo + Impulsado',
 ARRAY['Resumen de mentoría', 'Plan de cierre detallado'],
 'Meet / Presencial', 'Mentoría enfocada en cerrar el caso real en curso y definir la estrategia post-programa.',
 26),

('TEORIA_13', 'Formación extra — Estrategia de crecimiento personal',
 'fase_ii_seguimiento', 'teoria', 77, 84,
 'Gonzalo', 'Gonzalo',
 ARRAY['Plan de negocio personal a 12 meses'],
 'Teams / Drive', 'Cómo escalar el negocio tras el programa. Equipo, inversión y marca.',
 27),

('HITO_6', 'Negociación activa con comprador o vendedor',
 'fase_ii_seguimiento', 'hito', 77, 84,
 'Impulsado', 'Impulsado',
 ARRAY['Contrato de arras o señal tramitada'],
 'Notion / GoHighLevel', 'El impulsado está en negociación activa con una de las partes de la operación.',
 28),

('SESION_4', 'Sesión práctica 4 — Revisión de caso real en vivo',
 'fase_ii_seguimiento', 'sesion_practica', 84, 90,
 'Gonzalo', 'Gonzalo + Impulsado',
 ARRAY['Análisis del caso real', 'Próximos pasos definidos'],
 'Meet / Presencial', 'Análisis en profundidad del caso real del impulsado con el mentor.',
 29),

('CC3', 'Check Control 3 — Evaluación avanzada',
 'fase_ii_seguimiento', 'check_control', 84, 90,
 'Gonzalo + Laura', 'Gonzalo',
 ARRAY['Informe CC3', 'Valoración 360°'],
 'Meet', 'Evaluación con KCD del mes, pipeline actualizado y perspectiva de cierre.',
 30),

('HITO_7', 'Cierre o caso real consolidado',
 'fase_ii_seguimiento', 'hito', 84, 100,
 'Impulsado', 'Impulsado + Gonzalo',
 ARRAY['Operación cerrada o en firma', 'Informe de cierre'],
 'Notion', 'Hito culminante: operación cerrada o en proceso de firma notarial.',
 31),

('CC4', 'Check Control Final — KCD y cierre de programa',
 'fase_ii_seguimiento', 'check_control', 85, 95,
 'Gonzalo + Laura', 'Gonzalo',
 ARRAY['KCD final', 'Valoración del programa', 'Plan de seguimiento'],
 'Meet / Presencial', 'Cierre formal del programa. KCD final, reflexión y planificación post-Impulsa.',
 32),

('RESUMEN_MES_1', 'Resumen mensual — Mes 1',
 'fase_i_estrategia', 'resumen', 30, 30,
 'Laura', 'Sistema',
 ARRAY['Informe mensual PDF'],
 'Email / Drive', 'Informe mensual generado automáticamente con los datos del mes 1.',
 33),

('RESUMEN_MES_2', 'Resumen mensual — Mes 2',
 'fase_ii_seguimiento', 'resumen', 60, 60,
 'Laura', 'Sistema',
 ARRAY['Informe mensual PDF'],
 'Email / Drive', 'Informe mensual generado automáticamente con los datos del mes 2.',
 34),

('RESUMEN_MES_3', 'Resumen mensual — Mes 3 (cierre)',
 'fase_ii_seguimiento', 'resumen', 90, 90,
 'Laura', 'Sistema',
 ARRAY['Informe mensual PDF', 'Informe de cierre de programa'],
 'Email / Drive', 'Informe de cierre del programa con el resumen de los 3 meses.',
 35);
